#!/usr/bin/env bash
set -ex

source ./config.sh

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript -e "rmarkdown::render(input = 'DESeq2.Rmd', output_dir = '../results', clean = TRUE, params=list(alpha=$alpha, colNonSig='$colNonSig', colSig='$colSig'))"

# The previous version of this file was commented-out and follows below:
#
# Rscript deseq2.R "$@"
#  
# 
