#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript -e "rmarkdown::render(input = 'DESeq2.Rmd', output_dir = '../results', clean = TRUE)"

# The previous version of this file was commented-out and follows below:
#
# Rscript deseq2.R "$@"
#  
# 
